name: chainless_frontend
description: Serverless Functions for Blockchains
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  logging: ^1.2.0
  async: ^2.11.0
  fpdart: ^1.1.0
  rxdart: ^0.28.0
  fetch_client: ^1.0.2
  http: ^1.2.0
  code_editor: ^2.1.0
  omni_datetime_picker: ^1.0.9
  file_picker: ^8.0.0+1
  flutter_expandable_fab: ^2.0.0
  multi_dropdown: ^2.1.4
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  flutter_highlight: ^0.7.0
  provider: ^6.1.1
  syncfusion_flutter_charts: ^26.2.8
  date_time_format: ^2.0.1
  loading_indicator: ^3.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
