name: Publish Docker Images

on:
  workflow_call:
    inputs:
      dev_tag:
        description: 'Publish a development tag.'
        default: false
        required: false
        type: boolean
      latest_tag:
        description: 'Publish a latest tag.'
        default: false
        required: false
        type: boolean

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm-community'
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history to update last modified time.
      - name: git-restore-mtime
        uses: chetan/git-restore-mtime-action@v2
      - name: Cache project
        uses: actions/cache@v4
        with:
          path: |
            **/target/**
            !**/test-results/**
          key: ${{ format('{0}-project-{1}-{2}', runner.os, github.base_ref, github.run_number) }}

      - name: Download Frontend Dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: "backend/core/src/main/resources/web"

      - name: Print Static Web Files
        run: ls -la backend/core/src/main/resources/web

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images to registries
        working-directory: ./backend
        run: DOCKER_PUBLISH_DEV_TAG=${{ inputs.dev_tag }} DOCKER_PUBLISH_LATEST_TAG=${{ inputs.latest_tag }} sbt Docker/publish
